language: python
python:
    - "2.7"
    - "3.4"
    - "pypy"
env:
  - DJANGO_VERSION='>=1.7,<1.8'
  - DJANGO_VERSION='>=1.7,<1.8'
install:
    - pip install "Django${DJANGO_VERSION}"
    - pip install .
script:
    - PYTHONPATH=. DJANGO_SETTINGS_MODULE=test_project.settings django-admin test