language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
env:
  - DJANGO_VERSION='>=1.6,<1.7'
  - DJANGO_VERSION='>=1.5,<1.6'
install:
    - pip install "Django${DJANGO_VERSION}"
    - pip install .
script:
    - PYTHONPATH=. DJANGO_SETTINGS_MODULE=test_project.settings django-admin.py test